# Generated by Django 2.1 on 2018-08-12 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Logs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_text', models.CharField(max_length=2000)),
                ('pub_data', models.DateTimeField(verbose_name='published')),
            ],
        ),
    ]
