# Generated by Django 2.1 on 2018-08-12 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='logs',
            old_name='pub_data',
            new_name='data',
        ),
    ]
