# Generated by Django 2.1 on 2018-08-12 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Name',
        ),
        migrations.AddField(
            model_name='comment',
            name='name',
            field=models.CharField(default='nick', max_length=200),
        ),
    ]
